# Generated by Django 3.2.12 on 2023-03-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='badgename',
        ),
    ]
