# Generated by Django 3.2.12 on 2023-03-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_badge_badgename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnt_boarditems_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cnt_boards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cnt_boards_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cnt_groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cnt_rank1',
            field=models.IntegerField(default=0),
        ),
    ]
