# Generated by Django 3.2.12 on 2023-06-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_noti_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.IntegerField(default=1),
        ),
    ]
