version: "3"

services:
  _build_image:
    image: main_image
    build:
      context: ./backend
      dockerfile: ./Dockerfile

  backend:
    image: main_image
    container_name: backimg
    restart: always
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    depends_on:
      - _build_image
