# Generated by Django 3.2.12 on 2023-08-24 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.IntegerField(default=0)),
                ('rand_name', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=20)),
                ('background', models.IntegerField(null=True)),
                ('is_black', models.BooleanField(default=False)),
                ('has_border', models.BooleanField(default=False)),
                ('has_round_edge', models.BooleanField(default=False)),
                ('around_kan', models.IntegerField(default=0)),
                ('complete_icon', models.IntegerField(default=0)),
                ('font', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField(default=1)),
                ('headcount', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('size', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('rule', models.TextField(null=True)),
                ('has_img', models.BooleanField()),
                ('period', models.IntegerField()),
                ('is_public', models.BooleanField()),
                ('password', models.CharField(max_length=20, null=True)),
                ('need_auth', models.BooleanField()),
                ('leader', models.ForeignKey(on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', through='groups.Board', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('check', models.BooleanField()),
                ('check_goal', models.IntegerField(null=True)),
                ('check_cnt', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='groups.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
