# Generated by Django 3.2.12 on 2023-02-23 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(db_column='group_id', primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=20, unique=True)),
                ('headcount', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('size', models.IntegerField()),
                ('description', models.TextField()),
                ('rule', models.TextField()),
                ('has_img', models.BooleanField()),
                ('period', models.IntegerField()),
                ('is_public', models.BooleanField()),
                ('password', models.CharField(max_length=20, null=True)),
                ('need_auth', models.BooleanField()),
                ('leader', models.ForeignKey(on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
