# Generated by Django 3.2.12 on 2023-03-03 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=20, unique=True)),
                ('headcount', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('size', models.IntegerField()),
                ('description', models.TextField()),
                ('rule', models.TextField()),
                ('has_img', models.BooleanField()),
                ('period', models.IntegerField()),
                ('is_public', models.BooleanField()),
                ('password', models.CharField(max_length=20)),
                ('need_auth', models.BooleanField()),
                ('leader', models.ForeignKey(on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField()),
                ('rand_name', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
