# Generated by Django 3.2.12 on 2023-03-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='rule',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='participate',
            name='rand_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
