# Generated by Django 3.2.12 on 2023-03-13 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='users', through='groups.Participate', to=settings.AUTH_USER_MODEL),
        ),
    ]
