# Generated by Django 3.2.12 on 2023-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
