# Generated by Django 3.2.12 on 2023-03-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_chat_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
    ]
