# Generated by Django 3.2.12 on 2023-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20230918_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='check_goal',
            field=models.IntegerField(default=0),
        ),
    ]
