# Generated by Django 3.2.20 on 2023-10-23 06:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_alter_boarditem_check_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='board',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
