# Generated by Django 3.2.12 on 2023-05-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='is_banned',
            field=models.IntegerField(),
        ),
    ]
