# Generated by Django 3.2.12 on 2023-05-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_participate_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='is_banned',
            field=models.IntegerField(default=0),
        ),
    ]
