# Generated by Django 3.2.12 on 2023-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20230620_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
