# Generated by Django 3.2.12 on 2023-03-21 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('background', models.IntegerField(default=0)),
                ('is_black', models.BooleanField(default=False)),
                ('has_border', models.BooleanField(default=False)),
                ('has_round_edge', models.BooleanField(default=False)),
                ('around_kan', models.IntegerField(default=0)),
                ('complete_icon', models.IntegerField(default=0)),
                ('font', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('check', models.BooleanField()),
                ('check_goal', models.IntegerField()),
                ('check_cnt', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
    ]
