# Generated by Django 3.2.12 on 2023-02-23 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(db_column='board_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('background', models.IntegerField()),
                ('color_text', models.CharField(max_length=6)),
                ('color_line', models.CharField(max_length=6)),
                ('line_style', models.IntegerField()),
                ('font', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
