# Generated by Django 3.2.12 on 2023-03-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='check_cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boarditem',
            name='check_goal',
            field=models.IntegerField(null=True),
        ),
    ]
