# Generated by Django 3.2.12 on 2023-02-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('item_id', models.AutoField(db_column='item_id', primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('check', models.BooleanField()),
                ('check_goal', models.IntegerField()),
                ('check_cnt', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
    ]
