# Generated by Django 3.2.12 on 2023-05-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20230321_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background',
            field=models.IntegerField(null=True),
        ),
    ]
