# Generated by Django 3.2.12 on 2023-06-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_board_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='check_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
