// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfm5hN0s_IQBnU2tAvl1AQLk8zcJD9cPo',
    appId: '1:225967626004:web:3e60d9854d54f98c929401',
    messagingSenderId: '225967626004',
    projectId: 'bingot-2c712',
    authDomain: 'bingot-2c712.firebaseapp.com',
    storageBucket: 'bingot-2c712.appspot.com',
    measurementId: 'G-F51ZJFR387',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkP4mMtJTQb_uGWn-FYw69IRIGpd90ON4',
    appId: '1:225967626004:android:94eb1ff0570125ad929401',
    messagingSenderId: '225967626004',
    projectId: 'bingot-2c712',
    storageBucket: 'bingot-2c712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM_jc1SzJjO_hhtTATYx7qBarrU3uNrQA',
    appId: '1:225967626004:ios:0f5e6d380175cd0d929401',
    messagingSenderId: '225967626004',
    projectId: 'bingot-2c712',
    storageBucket: 'bingot-2c712.appspot.com',
    iosClientId: '225967626004-c8djb8dqut5avcc7df1pa657ciq7nr25.apps.googleusercontent.com',
    iosBundleId: 'com.example.binGot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM_jc1SzJjO_hhtTATYx7qBarrU3uNrQA',
    appId: '1:225967626004:ios:0f5e6d380175cd0d929401',
    messagingSenderId: '225967626004',
    projectId: 'bingot-2c712',
    storageBucket: 'bingot-2c712.appspot.com',
    iosClientId: '225967626004-c8djb8dqut5avcc7df1pa657ciq7nr25.apps.googleusercontent.com',
    iosBundleId: 'com.example.binGot',
  );
}
